### ISSUE TITLE
renderTopMenuNavbar

### ISSUE THREAD

**Issue by Gujionsen** [pkerspe/yii2-simple-cms#5]
Hi, I get this error 
**Setting unknown property: schallschlucker\simplecms\Frontend::renderTopMenuNavbar**
on both frontend and backend pages. 

When i delete these lines from 'modules' => 'simplecms_frontend' error disappears...
 'renderTopMenuNavbar' => true,
 'htmlTitlePrefix' => '', 
 'htmlTitleSuffix' => '',

What could be reason of this?

**Comment by pkerspe** [comment]
Do you need to remove only the line 

```
'renderTopMenuNavbar' => true,
```

or all three lines?

**Comment by pkerspe** [comment]
please post the modules secition of your frontend and backend main configuration, and also relevant parts of common config if applicable

**Comment by Gujionsen** [comment]
after removing 'renderTopMenuNavbar' => true, this error appears,
**Setting unknown property: schallschlucker\simplecms\Frontend::htmlTitlePrefix**
after removing 'htmlTitlePrefix' => '', I have this error.
**Setting unknown property: schallschlucker\simplecms\Frontend::htmlTitleSuffix**

so to rid of the errors it needs to remove all of them

```
`'renderTopMenuNavbar' => true,
'htmlTitlePrefix' => '',
'htmlTitleSuffix' => '',`
```

I am using basic template of yii2 and I have this code in config/web.php file 

```
`'modules' => [
    'simplecms_backend' => [
        'class' => 'schallschlucker\simplecms\Backend',
        'languageManager' => 'simplecmsLanguageManager',
        'cache' => 'cache',
        ],
    'simplecms_frontend' => [
        'urlPrefix' => 'cms', 
        'class' => 'schallschlucker\simplecms\Frontend',
        'languageManager' => 'simplecmsLanguageManager',
        'renderTopMenuNavbar' => true,
        'htmlTitlePrefix' => '',
        'htmlTitleSuffix' => '',
        'cache' => 'cache'
    ],
    'media_manager' => [
        'class' => 'schallschlucker\simplecms\MediaManager',
         ],
],
```

**Comment by pkerspe** [comment]
are there any more details in the exception? E.g. a stack trace with line numbers?

**Comment by Gujionsen** [comment]
there is errors screen

![cms_errors](https://cloud.githubusercontent.com/assets/11720178/14931028/5aa03308-0e79-11e6-83a9-1430fe36100c.jpg)

**Comment by pkerspe** [comment]
I used a fresh install of the basic yii2 template and tried to reproduce your reported issue. Unfortunately I do not get the described error.
Using Yii2 in Version 2.0.8 and with standard basic template.

Which Version of Yii2 are you using?

**Comment by pkerspe** [comment]
can you please post lines 20-40 from the file Frontend.php (vendor/schallschlucker/yii2-simple-cms/Frontend.php).

**Comment by Gujionsen** [comment]
I have installed it on latest 2.0.9-dev version of yii2 basic template. 
there is Frontend.php code. 21-43 lines

`class Frontend extends \yii\base\Module {
    const VERSION = '0.1';
    public $controllerNamespace = 'schallschlucker\simplecms\controllers\frontend';
    public $defaultRoute='show';
    public $languageManager;
    public $cache;

```
/**
 * @var string The prefix for user module URL.
 * @See [[GroupUrlRule::prefix]]
 */
public $urlPrefix = 'cms';

/**
 *
 * @var array The rules to be used in URL management.
 */
public $urlRules = [ 
    'home' => 'show/homepage',
    'page/<menuItemId:\d+>' => 'show/page',
    'c/<menuItemAlias:\w+>' => 'show/alias',
];
`
```

**Comment by pkerspe** [comment]
Thanks, that helped, I found the problem. 
The doucmentation of the configuration part was for the dev-master branch of simple-cms. I created a new release 0.2.4.3 which has the latest code and also the missing properties in the Frontend class.
Please update yii2-simple-cms using composer update to install the latest version and report back if the problem is fixed.

Thanks for your patience and feedback!

P.S: make sure you run

```
yii migrate --migrationPath=@schallschlucker/simplecms/migrations
```

 to update the db to be sure you have the latest required db layout.

**Comment by Gujionsen** [comment]
Thank you for your help and attention.
Old errors have gone, but I have new one. After clicking "Edit content" this error appears:

*_Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: schallschlucker\simplecms\models\CmsPageContent::render_subpage_teasers
*_

**Comment by Gujionsen** [comment]
Thank you, after migration everything is ok!
