### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by pdempsey** [pkerspe/yii2-simple-cms#6]
I get the following error on migration.

Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\console\ErrorHandler::errorAction'

No other migration has this issue.  The console command ran correctly and the module is installed.

I'm using RBAC.

**Comment by savefamilyphotos** [comment]
which exact version of yii2 are you using?

**Comment by pdempsey** [comment]
2.0.9  Running in Apache 2 WAMP PHP 5.5.12

**Comment by pdempsey** [comment]
Also using Yii2 Improved Application Templates

http://www.freetuts.org/tutorial/view?id=6
Extensions are RBAC and the advanced database User module.

**Comment by savefamilyphotos** [comment]
I checked the code and could not find any reference in the migration scripts to the mentioned property. Also in older yii2 versions this property did not exist.
Can you please post the complete exception with line numbers and the file where the exception was thrown?
Which migration script caused the issue excately? There are 3 so far in the simple cms repo.

**Comment by pdempsey** [comment]
yii migrate --migrationPath=@schallschlucker/simplecms/migrations

Fatal error: Uncaught exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\ErrorHandler::errorAction' in G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\base\Component.php on line 197

yii\base\UnknownPropertyException: Setting unknown property: yii\console\ErrorHandler::errorAction in G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\base\Component.php on line 197

Call Stack:
    0.0005     236696   1. {main}() G:\webroot2\yii2app\advanced_protected\yii:0
    0.3148    1425544   2. yii\console\Application->__construct() G:\webroot2\yii2app\advanced_protected\yii:28
    0.3149    1425760   3. yii\base\Application->__construct() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\console\Application.php:89
    0.3154    1434752   4. yii\base\Application->registerErrorHandler() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\base\Application.php:204
    0.3155    1435024   5. yii\console\Application->getErrorHandler() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\base\Application.php:335
    0.3156    1435264   6. yii\di\ServiceLocator->get() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\console\Application.php:210
    0.3156    1435488   7. yii\BaseYii::createObject() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\di\ServiceLocator.php:133
    0.3156    1436264   8. yii\di\Container->get() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\BaseYii.php:344
    0.3156    1436424   9. yii\di\Container->build() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\di\Container.php:154
    0.3220    1570512  10. ReflectionClass->newInstanceArgs() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\di\Container.php:379
    0.3220    1571208  11. yii\base\Object->__construct() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\di\Container.php:379
    0.3220    1571208  12. yii\BaseYii::configure() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\base\Object.php:105
    0.3220    1572096  13. yii\base\Component->__set() G:\webroot2\yii2app\advanced_protected\vendor\yiisoft\yii2\base\Object.php:521

**Comment by pdempsey** [comment]
One thing that helps is publishing a simple sql file people can use to create the database entries

I also tried installing the package in a clean Yii2 install (ver 2.09, freshly updated) the only module installed was RBAC and the basic user table used with it.   Same error on migration.

**Comment by pkerspe** [comment]
@pdempsey I finally added the db schema creation script to the git repo for people who experience issues with the migraiton scripts. Please find it in /doc/db_schema.sql (in master branch)
