### ISSUE TITLE
Change layout

### ISSUE THREAD

**Issue by infoitservit** [pkerspe/yii2-simple-cms#9]
Is it possible to choose the layout of the frontend pages?

**Comment by pkerspe** [comment]
Hello, no the layout is on purpose independent from the cms logic, since there won't be two websites having the same layout anyway. This is part of the general yii2 setup to create you own layouts.

**Comment by infoitservit** [comment]
Maybe i've not explained it so well. Your layout is ok, if i would like to change it would be better to operate ont the view file.
I mean, how should i apply a generale layout created? In my application i've 3 different layouts, one with a search bar on top, one "clean" without it and so on...
I just would like to apply it "around" the content generated by your module.
Usually i do it with "$this->context->layout = '@frontend/views/layouts/custom-layout';" within a view or i change it in controller
